# This file was generated by GoReleaser. DO NOT EDIT.
cask "ink" do
  name "ink"
  desc "Terminal markdown viewer and distraction-free editor"
  homepage "https://github.com/inkcheck/ink"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ink"

  on_macos do
    on_intel do
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_darwin_amd64.tar.gz"
      sha256 "d261591aa48349a7e674257eddc58caf3bf848fccb34937fc4b1f634e462ced5"
    end
    on_arm do
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_darwin_arm64.tar.gz"
      sha256 "7f44d98544570088e03bbeb2dcd1297863fb57f9d92648766cb2976da5a415e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_linux_amd64.tar.gz"
      sha256 "3d380f2ad8d52c3b1c18d13e8a05fc5fcc379cd797507a29654a62ced770fc8f"
    end
    on_arm do
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_linux_arm64.tar.gz"
      sha256 "95c60c3875685a2b9a9138d5572563e8d2bedd71769d305c415781c272257e93"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ink"]
    end
  end

  # No zap stanza required
end
