# This file was generated by GoReleaser. DO NOT EDIT.
cask "ink" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "9fb4ef9e991033f16adfdc2c0546b313fb5ec8d78ab1b467416bf25117b8b70d"
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2a1a56696dd49865866531bc11c63e522b8e42b4b2f2cc5d032c13d92d75fc0"
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a8abf4fb6ce3a460231d70ce082e22f52540633e3839fda65f4a4237a082c6f2"
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3062e529e5400212fcf90ab1b80621cab7988b9217c30faa2c29c9013a8ed25"
      url "https://github.com/inkcheck/ink/releases/download/v#{version}/ink_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ink"
  desc "Terminal markdown viewer and distraction-free editor"
  homepage "https://github.com/inkcheck/ink"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ink"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ink"]
    end
  end

  # No zap stanza required

end
