# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkcheck" do
  name "inkcheck"
  desc "Text analysis through structural, rhetorical, and semantic metrics"
  homepage "https://github.com/inkcheck/inkcheck"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkcheck"

  on_macos do
    on_intel do
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_darwin_amd64.tar.gz"
      sha256 "3c26c93738885cf8426a4289e90feaddc49e8141092b5858a7e9d2aae40eacc9"
    end
    on_arm do
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_darwin_arm64.tar.gz"
      sha256 "4abec8e45233fb6cf85eb65b8f19e6f8fc53f363f1036719301ddcb4f39e7290"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_linux_amd64.tar.gz"
      sha256 "24a68619c7c348ca58e8f02ebfb514789ee7bc545b60baa37f0921ced7759340"
    end
    on_arm do
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_linux_arm64.tar.gz"
      sha256 "87b96f9cf17eb0d36f261b3b5d4d4ae5ca9c594761bfdda5121272fed8d7409d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inkcheck"]
    end
  end

  # No zap stanza required
end
