# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkcheck" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "241a1af29adb4298cb25cd7b2d477cb2aad8dc234091ef7a0b5a1e130ba72eb1"
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "741efbe4dd162d65a06470ab3f8952d843b80953a886ab6b583c95763ff64b89"
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c96846c6f09f1c2cd96b10609f6037dc566b7a0933f9a6e7405a3aec788ec72d"
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf2796ab87a0c46ff8e9e087fd11a38a819b105b944a98fe6171548894699421"
      url "https://github.com/inkcheck/inkcheck/releases/download/v#{version}/inkcheck_#{version}_linux_amd64.tar.gz"
    end
  end

  name "inkcheck"
  desc "Text analysis through structural, rhetorical, and semantic metrics"
  homepage "https://github.com/inkcheck/inkcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkcheck"

  # No zap stanza required
end
