# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkline" do
  version "0.1.0"

  on_macos do
    sha256 "8330dcf2cdd27d18ddbf568646dc31c689a60e6fda291ab59ea17509e7c30b46"
    url "https://github.com/inkcheck/inkline/releases/download/v#{version}/inkline_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "c0f2a1e2b37cf102905e5e578da2f67bea7e35c3de05116d4aec4007a2d87317"
      url "https://github.com/inkcheck/inkline/releases/download/v#{version}/inkline_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "06cd94656649cc1d0bd3a96339cf6d73c5555afe557bf01555b339b0a878a824"
      url "https://github.com/inkcheck/inkline/releases/download/v#{version}/inkline_#{version}_linux_amd64.tar.gz"
    end
  end

  name "inkline"
  desc "Text-first technical diagrams on D2, styled by pluggable design systems."
  homepage "https://github.com/inkcheck/inkline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkline"

  # No zap stanza required
end
