# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkpress" do
  version "0.2.0"

  on_macos do
    sha256 "350692b79e8bdd7e54b371fb20f62587ffa28ce904c95a322c08aad880251e97"
    url "https://github.com/inkcheck/inkpress/releases/download/v#{version}/inkpress_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "2f462eb44db4c1b14b23080cbc0cdabce9e3efcc33a33cf90f1a51d474a2054e"
      url "https://github.com/inkcheck/inkpress/releases/download/v#{version}/inkpress_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5b56e4642fbc8ec9fe6ddeaa3d1f1d2b3ae72af4e0f92cfff9fd83d2ddb5b37f"
      url "https://github.com/inkcheck/inkpress/releases/download/v#{version}/inkpress_#{version}_linux_amd64.tar.gz"
    end
  end

  name "inkpress"
  desc "Markdown slides to PDF, printed by an installed Chromium-based browser."
  homepage "https://github.com/inkcheck/inkpress"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkpress"

  # No zap stanza required
end
