# This file was generated by GoReleaser. DO NOT EDIT.
cask "inkpress" do
  version "0.1.0"

  on_macos do
    sha256 "d0d99fe27a79549509aa7716060cfa619c538d468445a26b93154f47c92977a8"
    url "https://github.com/inkcheck/inkpress/releases/download/v#{version}/inkpress_#{version}_darwin_universal.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "f6c8a4422371e771e80ceb23ca4037640ff9e4751b5693517abeb27fb7bef2d8"
      url "https://github.com/inkcheck/inkpress/releases/download/v#{version}/inkpress_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d73a192387cab419d556b4755ac5dd1a6faaed1dc2f80c2536a9effacd91fea"
      url "https://github.com/inkcheck/inkpress/releases/download/v#{version}/inkpress_#{version}_linux_amd64.tar.gz"
    end
  end

  name "inkpress"
  desc "Markdown slides to PDF, printed by an installed Chromium-based browser."
  homepage "https://github.com/inkcheck/inkpress"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "inkpress"

  # No zap stanza required
end
