# This file was generated by GoReleaser. DO NOT EDIT.
cask "readability" do
  name "readability"
  desc "Readability metrics for text analysis"
  homepage "https://github.com/inkcheck/readability"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readability"

  on_macos do
    on_intel do
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_darwin_amd64.tar.gz"
      sha256 "ac0ed349f6e3af616c1880a22dd790af8572f134d906997e7840a2594dcb6969"
    end
    on_arm do
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_darwin_arm64.tar.gz"
      sha256 "ed0c2dd5e302c336e34dae0a4152b41837408b1c952b4fac5fc4bcaaeea93bf3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_linux_amd64.tar.gz"
      sha256 "2b1aaea14ab18ec9064d5d389473f31d7eea4af7076e6d1b6b8163a68fc440b0"
    end
    on_arm do
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_linux_arm64.tar.gz"
      sha256 "3fbde5361d6b48c5458cecaff422c94246e5f65d4817d0132493c797e2d10dcc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/readability"]
    end
  end

  # No zap stanza required
end
