# This file was generated by GoReleaser. DO NOT EDIT.
cask "readability" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "0a7dbc98278dda6889ed0c1720a8bba898621ddb8598240f682d90b272c5065e"
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "771faa3fa3ec8f33c20a03d141e2a7b65528f724dc9dffb962eb49e706770545"
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5381afca89f99ac498980085070fd936a9f4e8dc0ddeb7db43e8500c7ab81b9"
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9cd6dc5296fe64aa3c4274990c1ef75a05989f5a73d8d3a250f35d0ebef092c5"
      url "https://github.com/inkcheck/readability/releases/download/v#{version}/readability_#{version}_linux_amd64.tar.gz"
    end
  end

  name "readability"
  desc "Readability metrics for text analysis"
  homepage "https://github.com/inkcheck/readability"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "readability"

  # No zap stanza required
end
